/// <reference types="pixi.js" />
export declare type ScrollItemOptions = {
    container: PIXI.Container;
    onClick?: Function;
};
import { ValidMeasurement } from "../../types";
export declare type ScrollStyleOptions = {
    width?: ValidMeasurement;
    height?: ValidMeasurement;
    backgroundColor: number;
    dividerColor: number;
    dividerPixelHeight: number;
    dividerPercentWidth: number;
    dividerTopPadding: number;
    dividerBottomPadding: number;
    borderOpacity: number;
    xPadding: number;
    yPadding: number;
    scrollBarWidth: number;
    scrollBarSide: "left" | "right";
};
export declare type ScrolllPerformanceOptions = {
    visibilityBuffer: number;
    adjustVisibilityTime: number;
};
export declare class ScrollList extends PIXI.Container {
    private scrollStyleOptions;
    private scrollItemsById;
    private options;
    private po;
    private scrollBar;
    private scrollbarScroll;
    private scrollRect;
    private scrollDuration;
    private scrollMask;
    private _currentScroll;
    private lastScroll;
    private __width;
    private __height;
    private pointerdownStart;
    private startingVisibleChildIndex;
    private endingVisibleChildIndex;
    private scrollCurrentDur;
    private currentAdjustVisibilityDelta;
    private animationFrame;
    private nextItemY;
    private scrollToDest;
    private listContainer;
    private listRect;
    private scrollLength;
    private adjustedIndex;
    private maxHeight;
    private lastOverOption;
    private lastDownOption;
    private tweenFunc;
    readonly performanceOptions: ScrolllPerformanceOptions;
    constructor(scrollStyleOptions: ScrollStyleOptions, scrollItemOptions: Array<ScrollItemOptions>, scrollPerformanceOptions?: ScrolllPerformanceOptions);
    private findVisible;
    private _containsPoint;
    private findOptionAtPoint;
    private relayEvent;
    private redraw;
    private repositionOptions;
    private adjustVisibility;
    private adjustOptions;
    private animateScroll;
    private applyDrag;
    private applySwipe;
    currentScroll: any;
    addScrollItems(containers: Array<PIXI.Container>): void;
    addScrollItem(container: PIXI.Container): void;
    removeScrollItem(indexOrContainer: any): boolean;
    private initializeEventPropogation;
}
